# Generated by Django 5.1.6 on 2025-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('ce', 'Computer Engineering'), ('ec', 'Electronics & Communication'), ('ch', 'Chemical Engineering'), ('me', 'Mechanical Engineering'), ('mh', 'Mechatronics Engineering')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('mbbs', 'MBBS'), ('msc', 'M.Sc'), ('bsc', 'B.Sc'), ('ba', 'B.A'), ('ma', 'M.A')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty_type',
            field=models.CharField(blank=True, choices=[('technology', 'Faculty of Technology'), ('medical', 'Faculty of Medical Science'), ('MBA', 'Faculty of Management Studies'), ('arts', 'Faculty of Arts')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
