# Generated by Django 5.1.6 on 2025-02-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageAuth', '0002_create_default_roles'),
        ('HomePageAuth', '0002_remove_passwordreset_user_and_more'),
    ]

    operations = [
    ]
